// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bexzdbdhikpywtlduujb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJleHpkYmRoaWtweXd0bGR1dWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTEyODIsImV4cCI6MjA1ODIyNzI4Mn0.-970MlOTgQUWoC9Y-R2_IC7V7ZHC1PlPkPPrK__KX6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);